version: '3.8'

services:
  appointment-service:
    build:
      context: ./backend/appointment-service
      target: dev

    environment:
      DATABASE_HOST: database
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_SYNC: ${DATABASE_SYNC}
      API_PORT: ${API_PORT}

    ports:
      - ${API_PORT}:${API_PORT}

    volumes:
      - ./backend/appointment-service/src:/opt/app/src

    depends_on:
      - database

  database:
    image: 'postgres:17.4-alpine'

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - care-plan-db:/var/lib/postgresql/data/

    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database

volumes:
  care-plan-db:
