version: '3.8'

services:
  appointment-service:
    build:
      context: ./backend/appointment-service
      target: dev
    volumes:
      - ./backend/appointment-service/src:/opt/app/src

  database:
    image: 'postgres:17.4-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
