version: '3.8'

services:
  appointment-service:
    build:
      context: ./backend/appointment-service
      target: dev
    volumes:
      - ./backend/appointment-service/src:/opt/app/src

  database:
    image: 'postgres:17.4-alpine'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - care-plan-db:/var/lib/postgresql/data/

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database

volumes:
  care-plan-db:
