#!/usr/bin/env bash

echo "Update..."
git pull

echo "Stopping containers..."
make dev-stop

echo "Cleaning current images..."
make dev-clean

echo "Starting app on development environment..."
#make dev
