#!/usr/bin/env bash

set -e

: ${DIR_NAME:=./care-plan}
: ${BRANCH:=predeploy}
: ${CMD_RUN:=predeploy}
: ${DOCKER_COMPOSE:=docker compose}

if [[ ! -d $DIR_NAME ]]; then
   echo "Directory $DIR_NAME does not exist."
   exit 1
fi

cd $DIR_NAME

current=$(git branch | grep "\*" | awk '{print $2}')

if [[ "$current" != "$BRANCH" ]]; then
   echo "Switching to branch $BRANCH..."
   git switch origin $BRANCH
fi

export DOCKER_COMPOSE
git pull origin $BRANCH

echo "Starting app on development environment..."
make $CMD_RUN
