#!/usr/bin/env bash

DEPLOY_PATH="/home/ubuntu/care-plan"

if [ ! -d "$DEPLOY_PATH" ]; then
    echo "Directory $DEPLOY_PATH does not exist."
    exit 1
fi

echo "Deploy directory $DEPLOY_PATH"
cd "$DEPLOY_PATH"

echo "Update..."
git pull origin predeploy

echo "Stopping containers..."
make stop

echo "Cleaning current images..."
make clean

echo "Starting app on development environment..."
#make dev
